articles/urls.py
from django.urls import path

from .views import (
    article_create_view,
    article_detail_view,
    article_search_view
)

app_name = "articles"
urlpatterns = [
    path('', article_search_view, name="search"),
    path('create/', article_create_view, name = 'create'),
    path('<slug:slug>', article_detail_view, name='detail'),
]

management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from accounts.views import (
    login_view,
    logout_view,
    register_view,
)

from .views import home_view
from meals.views import meal_queue_toggle_view
from search.views import search_view

urlpatterns = [
    #Home
    path('', home_view),
    #Admin
    path('admin/', admin.site.urls),
    #Accounts
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
    #Articles
    path('articles/', include('articles.urls')),
    #Meals
    path('meal-toggle/<int:recipe_id>', meal_queue_toggle_view, name='meal-toggle'),
    #Recipes
    path('pantry/recipes/', include('recipes.urls')),
    #Search
    path('search/', search_view, name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from .views import (
    recipe_create_view,
    recipe_delete_view,
    recipe_detail_view,
    recipe_list_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingredient_delete_view,
    recipe_ingredient_image_upload_view,
    recipe_ingredient_update_hx_view,

)

app_name = 'recipes' #recipes:list

urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),
    #HX views
    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingredient_update_hx_view, name='hx-ingredient-update'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name='hx-ingredient-create'),
    path("hx/<int:id>/", recipe_detail_hx_view, name='hx-detail'),
    #Standard views
    path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view, name='recipe-ingredient-image-upload'),
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_ingredient_delete_view, name='ingredient-delete'),
    path("<int:id>/delete/", recipe_delete_view, name='delete'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view, name='detail'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--BootStrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!--HTMX-->
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/recipes/recipes-htmx.css' %}"/>
    <title>Incroyable app</title>
  </head>
  <body>
    {% include 'base/navbar.html' %}
    <!--Change the format according the class is container OR container-fluid (it's possible to change it on navbar.html too)-->
    <div class="container">
      {% if user.is_authenticated %}
      <p>Your are logged in as {{ user.username|title }}</p>
      {% endif %}
      {% block content %}
          <h3>This will be replaced</h3>
      {% endblock %}
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
      })
      //Replace the part below on recipes/ppartial/detail to avoid to always to deal with headers forms needing csrf_token
      //{% comment %} hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' {% endcomment %}
    </script>
  </body>
</html>

templates/home-view.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ object.title }} (id = {{ id }})</h1>
  <p>{{ object.content }}</p>

  <a href="{% url 'articles:create' %}">Create Article</a>
  <a href="{% url 'recipes:list' %}">Recipes List</a>
  <ul>
    {% for obj in object_list %}
      <li>
        {% comment %} <a href="{% url 'article-detail' slug=obj.slug %}">{{ obj.title }} - {{ obj.content }} - {{ obj.id }}</a> {% endcomment %}
        <a href="{{ obj.get_absolute_url }}">{{ obj.title }} - {{ obj.content }} - {{ obj.id }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/image-form.html
{% extends 'base.html' %}

{% block content %}
  <form action="." method="POST" enctype="multipart/form-data" hx-post="{{ request.path }}" hx-encoding="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button style="margin-top:10px;" type="submit">Upload image</button>
  </form>
{% endblock %}